Space travelers' Hub Project
andersonlebon/Space-Travelers-Hub pull request #32
Opened 2021-09-08 14:42 UTC by eroiyo

## Features

- [ ] Rocket session

-The rocket session features a rocket list that contain a list of cards displaying information about the rockets
like images, and a description, you can reserve any rockect that is in the page

- [ ] Mission  session

-The mission sessions features, a table, the table contain missions names and descriptions
you can confirm that you will attempt any of these missions

- [ ] My Profile Session

-This session features 2 tables, one containing all the names of the reserved rockets and the other that have the names
of the missions, the user will attemp

Thanks for reading!

2021-09-08 16:09 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @andersonlebon   and @eroiyo  

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Git/GitHub flow best practices have been followed. :heavy_check_mark:
- You have a descriptive Readme file.:heavy_check_mark:
- Your project looks nice:heavy_check_mark:
- The YouTube video explains all features we have in the project:heavy_check_mark:
- All links are working properly:heavy_check_mark:
- All button actions are working properly:heavy_check_mark:

Changes required :writing_hand: 

    * #### Please check the comments under the review.
       
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-08 16:09 UTC, Emmyn5600 commented on src/App.test.js
> +});
- [ ] All tests are not passing, kindly work on it to make all tests running.

![week3](https://user-images.githubusercontent.com/55635977/132541586-044ebe40-2b1b-463a-b16e-e39a2e42fe0a.png)


- [x] I suggest you to work on the Mission and Rockets testing to test if it renders with their links successfully.

2021-09-08 16:09 UTC, Emmyn5600 commented on package.json
> +}
- [x] In the Config & basic setup, you are missing the React Logger to let you replay problems as if they happened in your own browser. Instead of guessing why errors happen, or asking users for screenshots and log dumps.

![week5](https://user-images.githubusercontent.com/55635977/132542236-11a861b9-4cd8-4278-b665-657445e1d1d7.png)

2021-09-08 16:09 UTC, Emmyn5600 commented on src/components/common/mission.jsx
> +/* eslint-disable react/jsx-indent-props */
- [x] Fix eslint errors without disabling some lines of code

2021-09-08 16:09 UTC, Emmyn5600 commented on src/components/rockets.jsx
> +/* eslint-disable react/prop-types */
- [x] Fix eslint errors without disabling some lines of code

2021-09-08 16:09 UTC, Emmyn5600 commented on src/redux/mission/mission.js
> +/* eslint-disable camelcase */
- [x] Fix eslint errors without disabling some lines of code

2021-09-08 16:09 UTC, Emmyn5600 commented on src/redux/configurestore.js
> +export default store;
- [x] Remove commented line in the code that has been pushed.

2021-09-08 16:09 UTC, Emmyn5600 commented on src/redux/mission/mission.js
> +export default slice.reducer;
- [ ] Optional suggestions

According to the way you have implemented your logic (actions, reducers and API), my suggestion to modify our logic to add actions and reducers folder for a better implementation may force you to change everything. So I suggest you to check for this pattern I showed you to make a clear implementation in our next project.

You have implemented actions, reducers and fetch api data in a single file, to keep our code clean and clear, let us modify our file like this :point_down: 

         * I recommend you to create two folders (reducers and actions) in the redux folder.

- The action folder will keep the actions `type and created`
- The Reducer will keep the cases as well as initialState we need to implement .


### For more details check this.

-  Great implementation here, however, let us modify our structure in this way, the below structure will help us to split out the different actions in different folders not in one folder as you did in the `src/redux/missions/missions.js`

Create two folders in the redux folder: 

- Actions
    - actiontypes.js
       - export const SUCCESS_MISSION = 'SUCCESS_MISSION';
       - export const JOIN_MISSION = 'JOIN_MISSION';
    - actioncreator.js
       - export const successMission = (payload) => ({
       type: SUCCESS_MISSION,
       payload,
       });
- Reducers to keep the initialState and our cases
    - missionReducer.js
    - rocketReducers.js
    
The above structure will help us to make a clear implementation of our tasks as well as to create many actions to be implemented as long as we have a big project.

2021-09-08 16:09 UTC, Emmyn5600 commented on src/redux/rockets/rockets.js
> +export default slice.reducer;
- [ ] Optional suggestions

According to the way you have implemented your logic (actions, reducers and API), my suggestion to modify our logic to add actions and reducers folder for a better implementation may force you to change everything. So I suggest you to check for this pattern I showed you to make a clear implementation in our next project.s.

You have implemented actions, reducers and fetch api data in a single file, to keep our code clean and clear, let us modify our file like this :point_down: 

         * I recommend you to create two folders (reducers and actions) in the redux folder.

- The action folder will keep the actions `type and created`
- The Reducer will keep the cases as well as initialState we need to implement .


### For more details check this.

-  Great implementation here, however, let us modify our structure in this way, the below structure will help us to split out the different actions in different folders not in one folder as you did in the `src/redux/missions/missions.js`

Create two folders in the redux folder: 

- Actions
    - actiontypes.js
       - export const SUCCESS_MISSION = 'SUCCESS_MISSION';
       - export const JOIN_MISSION = 'JOIN_MISSION';
    - actioncreator.js
       - export const successMission = (payload) => ({
       type: SUCCESS_MISSION,
       payload,
       });
- Reducers to keep the initialState and our cases
    - missionReducer.js
    - rocketReducers.js
    
The above structure will help us to make a clear implementation of our tasks as well as to create many actions to be implemented as long as we have a big project.

2021-09-08 18:31 UTC, andersonlebon commented on src/App.test.js
> +});
Thanks for this review. We will cover it but this was not required

2021-09-08 18:34 UTC, andersonlebon commented on package.json
> +}
Okey. That is nice, we did not put the Redux logger because we use the redux-dev-tools for debugging if a bug occurs.But we will add it.

2021-09-08 18:38 UTC, andersonlebon commented on src/redux/mission/mission.js
> +export default slice.reducer;
We kindly use the same pattern as last week. We used the [ducks pattern](https://github.com/erikras/ducks-modular-redux)

2021-09-08 18:47 UTC, Emmyn5600 commented on src/redux/mission/mission.js
> +export default slice.reducer;
I see you have followed the same pattern `ducks pattern`, however, you are creating and implementing actions, reducers and API in the same file. Imagine the time you are working on the big project that has many actions, do you think to implement all in the same file is a good practice.

2021-09-08 18:48 UTC, andersonlebon commented on src/redux/mission/mission.js
> +export default slice.reducer;
![Screenshot from 2021-09-08 20-46-56](https://user-images.githubusercontent.com/65068771/132567333-810cfe2f-73c4-4fc0-b567-d71b6f3b8212.png)

- [ ] this was the structure of the Redux store learned last week.

2021-09-08 18:50 UTC, andersonlebon commented on src/redux/mission/mission.js
> +export default slice.reducer;
With this pattern, the reducer, action types, and action creators should be implemented in one file if they cover the same logic

2021-09-08 18:53 UTC, andersonlebon commented on src/redux/mission/mission.js
> +export default slice.reducer;
And we used a powerful Redux tool called [redux/toolkit ](https://redux-toolkit.js.org/). This tool simplifies the redux code,

2021-09-08 18:57 UTC, Emmyn5600 commented on src/redux/mission/mission.js
> +export default slice.reducer;
You can keep your structure as well however you can create two folders in the redux to keep the reducer and actions.

2021-09-08 19:01 UTC, andersonlebon commented on src/redux/mission/mission.js
> +export default slice.reducer;
But in the ducks pattern, they should be together.

2021-09-08 19:06 UTC, Emmyn5600 commented on src/redux/mission/mission.js
> +export default slice.reducer;
That should work also, like to create actions and reducers folders in the mission and rocket folder.
![complain](https://user-images.githubusercontent.com/55635977/132569821-01b08982-c15d-4d6b-80e7-78e0df78c1d0.png)

2021-09-09 08:56 UTC, AshakaE approved these changes
### Hi @andersonlebon & @eroiyo  🙋‍♀️, 

# STATUS APPROVED ✔
Thanks for making the required changes
Overall great project 👍 
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 09:05 UTC, merged